language: node_js
sudo: false

cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g npm@latest

node_js:
  - "6"
  - "8"

script:
- npm run lint
- npm run test

after_success:
- npm run coveralls
